name = "mingxian"
compatibility_date = "2026-05-03"
pages_build_output_dir = "."

[vars]
ASTRO_API_BASE = "https://astro-node-api.onrender.com"
OPENAI_MODEL = "gpt-5.5-mini"
CF_AI_MODEL = "@cf/ibm-granite/granite-4.0-h-micro"

[[kv_namespaces]]
binding = "MINGXIAN_STORE"
id = "41b9f8ea734d4874bc6ad14eee7e3a74"

[ai]
binding = "AI"
