services:
  - type: web
    name: astro-node-api
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 4318
